'use strict';
// =============================================
// MAIN GAME
// =============================================
const Game = {
  canvas:null, ctx:null, miniCanvas:null, miniCtx:null,
  running:false, paused:false, lastTime:0,
  player:null, enemies:[], items:[], projectiles:[], minions:[],
  dungeon:null, floor:1, totalKills:0, totalGold:0, gameTime:0,
  endlessMode:false,
  floorAffix:null,
  _arenaRemaining:0,
  _arenaRewardX:null,
  _arenaRewardY:null,
  _minionsRaised:0,
  _minionKills:0,
  _corpseBurstsCast:0,
  _darkPactsCast:0,
  _scrollsUsed:0,
  _bossKills:0, _maxCombo:0, _mysticEvents:0, _shadowWellsUsed:0,
  _echoVisions:0,
  _shadowDances:0,
  _wellEchoes:0,
  _mirageElitesSlain:0,
  _mirrorExecutorsSlain:0,
  _mirrorAssassinsSlain:0,
  _mirrorPriestessesSlain:0,
  _mirrorHeraldsSlain:0,
  _mirrorLancersSlain:0,
  _mirrorWeaversSlain:0,
  _riftboundElitesSlain:0,
  _riftReaversSlain:0,
  _riftSowersSlain:0,
  _obeliskboundElitesSlain:0,
  _obeliskSentinelsSlain:0,
  _obeliskAugursSlain:0,
  _riftBurstsCast:0,
  _riftBurstHits:0,
  _riftGuardsCast:0,
  _riftGuardHits:0,
  _riftBladesCast:0,
  _riftBladeHits:0,
  _obeliskLancesCast:0,
  _obeliskLanceHits:0,
  _obeliskCrashesCast:0,
  _obeliskCrashHits:0,
  _obeliskFansCast:0,
  _obeliskFanHits:0,
  _earthsplittersCast:0,
  _earthsplitterHits:0,
  _teleportsCast:0,
  _teleportDistance:0,
  _stealthCasts:0,
  _stealthSeconds:0,
  _rageCasts:0,
  _rageSeconds:0,
  _shieldAoeCasts:0,
  _shieldAoeHits:0,
  _fireballCasts:0,
  _fireballHits:0,
  _chainCasts:0,
  _chainHits:0,
  _beamCasts:0,
  _voidstepCasts:0,
  _voidstepExecutes:0,
  _mirrorBladeProcs:0,
  _mirrorBladeKills:0,
  _mirrorBladeCooldown:0,
  _mirrorVeilProcs:0,
  _mirrorVeilKills:0,
  _mirrorVeilCooldown:0,
  _mirrorEchoProcs:0,
  _mirrorEchoKills:0,
  _mirrorEchoCooldown:0,
  _mirrorPotionUses:0,
  _mirrorPotionKills:0,
  _mirrorPotionTimer:0,
  _riftPulseProcs:0,
  _riftPulseKills:0,
  _riftPulseCooldown:0,
  _riftAegisProcs:0,
  _riftAegisKills:0,
  _riftAegisCooldown:0,
  _riftPotionUses:0,
  _riftPotionKills:0,
  _riftSlashProcs:0,
  _riftSlashKills:0,
  _riftSlashCooldown:0,
  _obeliskEchoProcs:0,
  _obeliskEchoKills:0,
  _obeliskEchoCooldown:0,
  _obeliskWardProcs:0,
  _obeliskWardKills:0,
  _obeliskWardCooldown:0,
  _obeliskWardTimer:0,
  _obeliskStrikeProcs:0,
  _obeliskStrikeKills:0,
  _obeliskStrikeCooldown:0,
  _obeliskPotionUses:0,
  _obeliskPotionKills:0,
  _obeliskPotionTimer:0,
  _mirrorDashSurvived:0,
  _riftNovaSurvived:0,
  _obeliskStormSurvived:0,
  _shadowAwakenings:0,
  _wellSustainBlessings:0,
  _wellSustainVictories:0,
  _beamImpacts:0,
  _backstabCasts:0,
  _backstabKills:0,
  _shadowstepCasts:0,
  _shadowstepFinishes:0,
  _mirrorDashBossKills:0,
  _riftNovaBossKills:0,
  _obeliskStormBossKills:0,
  _bossLegendaryDrops:0,
  _potionsUsed:0,
  _flawlessVictories:0,
  _shopPurchases:0,
  _shopSales:0,
  _chestsOpened:0,
  _shrineUses:0,
  _stairsDescended:0,
  _levelUpsGained:0,
  _spellsCast:0,
  _meleeHits:0,
  _specialAttacksUsed:0,
  _dodgesPerformed:0,
  _meleeCrits:0,
  _rangedHits:0,
  _enemyProjectileHitsTaken:0,
  _eliteKills:0,
  _itemsPickedUp:0,
  _goldPickups:0,
  _hazardHitsTaken:0,
  _hitsTaken:0,
  _ringEquips:0,
  _weaponEquips:0,
  _armorEquips:0,
  _itemsDropped:0,
  _abyssRiftsUsed:0,
  _riftEmpowerments:0,
  _voidObelisksUsed:0,
  _obeliskBoons:0,
  _wellMercyCharges:0,
  _wellSustainTimer:0,
  _lastRelicFloor:0, _lastWellFloor:0, _lastRiftFloor:0, _lastObeliskFloor:0,
  _fpsSmoothed:60,
  _eventSpawnTrace:null,
  particles:new ParticleSystem(), floatingText:new FloatingText(),
  screenFX:new ScreenFX(), sound:new SoundFX(),
  mouseX:0, mouseY:0, mouseWorldX:0, mouseWorldY:0,
  keys:{}, camX:0, camY:0, camTargetX:0, camTargetY:0,
  animTime:0, ambientPhase:0,
  _hudEls:null, _hudCache:null, _buffHtmlCache:'',
  _minimapElapsed:0, _minimapInterval:.12, _minimapDirty:true,
  _inventoryVersion:0, _inventoryUIKey:'', _shopUIKey:'',
  _quickslotsDirty:true, _quickslotsCacheKey:'', _quickslotCounts:{hp:0,mp:0},
  _feedbackGate:{},
  _bloodStainSet:null, _bloodStainSource:null, _bloodStainCount:-1,
  _debugOverlayKey:'',
  _debugOverlayVisible:loadDebugOverlayVisible(),

};
