'use strict';
Object.assign(Game, {
  _ensureHudRefs(){
    if(this._hudEls)return;
    this._hudEls={
      name:document.getElementById('hud-name'),
      hpBar:document.getElementById('hp-bar'),
      hpText:document.getElementById('hp-text'),
      mpBar:document.getElementById('mp-bar'),
      mpText:document.getElementById('mp-text'),
      xpBar:document.getElementById('xp-bar'),
      xpText:document.getElementById('xp-text'),
      atk:document.getElementById('hud-atk'),
      def:document.getElementById('hud-def'),
      gold:document.getElementById('hud-gold'),
      floor:document.getElementById('hud-floor'),
      kills:document.getElementById('hud-kills'),
      buffBar:document.getElementById('buff-bar'),
      quickslots:document.getElementById('quickslots'),
      debugOverlay:document.getElementById('debug-overlay')
    };
  },

  _resetUICaches(){
    this._hudCache=null;
    this._buffHtmlCache='';
    this._minimapElapsed=this._minimapInterval;
    this._minimapDirty=true;
    this._inventoryVersion=0;
    this._inventoryUIKey='';
    this._shopUIKey='';
    this._quickslotCounts={hp:0,mp:0};
    this._quickslotsCacheKey='';
    this._quickslotsDirty=true;
    this._feedbackGate={};
    this._bloodStainSet=null;
    this._bloodStainSource=null;
    this._bloodStainCount=-1;
    this._debugOverlayKey='';
  },

  _getBloodStainSet(){
    const stains=(this.dungeon&&Array.isArray(this.dungeon.bloodStains))?this.dungeon.bloodStains:[];
    if(this._bloodStainSource!==stains||this._bloodStainCount!==stains.length){
      this._bloodStainSource=stains;
      this._bloodStainCount=stains.length;
      this._bloodStainSet=new Set(stains.map(b=>`${b.x},${b.y}`));
    }
    return this._bloodStainSet||new Set();
  },

  _combatFeedback(key,message,cls='info',cooldown=.6){
    const now=performance.now();
    const next=this._feedbackGate[key]||0;
    if(now<next)return false;
    this._feedbackGate[key]=now+cooldown*1000;
    this.log(message,cls);
    return true;
  },

  _applyDebugOverlayVisibility(){
    this._ensureHudRefs();
    if(!this._hudEls||!this._hudEls.debugOverlay)return;
    this._hudEls.debugOverlay.style.display=this._debugOverlayVisible?'block':'none';
  },

  toggleDebugOverlay(){
    this._debugOverlayVisible=!this._debugOverlayVisible;
    saveDebugOverlayVisible(this._debugOverlayVisible);
    this._applyDebugOverlayVisibility();
    this._showToast(this._debugOverlayVisible?'Panel debug: ON':'Panel debug: OFF','#8cf');
  },

  _refreshTitleDebugKeyHint(){
    const el=document.getElementById('title-debug-key');
    if(!el)return;
    el.textContent=getKeyDisplay(KeyBindings.debugOverlay||DEFAULT_KEYS.debugOverlay||'F3');
  },
  
  // ---- START ----
  start(playerClass){
    ContentRegistry.init();
    document.getElementById('title-screen').style.display='none';
    this.canvas=document.getElementById('gameCanvas');
    this.ctx=this.canvas.getContext('2d');
    this.miniCanvas=document.getElementById('minimap');
    this.miniCtx=this.miniCanvas.getContext('2d');
    
    this.resize();
    window.addEventListener('resize',()=>this.resize());
    
    this.playerClass=playerClass;
    this.endlessMode=false;
    this.minions=[];
    this._minionsRaised=0;
    this._minionKills=0;
    this._corpseBurstsCast=0;
    this._darkPactsCast=0;
    this._scrollsUsed=0;
    this._mysticEvents=0;
    this._shadowWellsUsed=0;
    this._echoVisions=0;
    this._shadowDances=0;
    this._wellEchoes=0;
    this._mirageElitesSlain=0;
    this._mirrorExecutorsSlain=0;
    this._mirrorAssassinsSlain=0;
    this._mirrorPriestessesSlain=0;
    this._mirrorHeraldsSlain=0;
    this._mirrorLancersSlain=0;
    this._mirrorWeaversSlain=0;
    this._riftboundElitesSlain=0;
    this._riftReaversSlain=0;
    this._riftSowersSlain=0;
    this._obeliskboundElitesSlain=0;
    this._obeliskSentinelsSlain=0;
    this._obeliskAugursSlain=0;
    this._riftBurstsCast=0;
    this._riftBurstHits=0;
    this._riftGuardsCast=0;
    this._riftGuardHits=0;
    this._riftBladesCast=0;
    this._riftBladeHits=0;
    this._obeliskLancesCast=0;
    this._obeliskLanceHits=0;
    this._obeliskCrashesCast=0;
    this._obeliskCrashHits=0;
    this._obeliskFansCast=0;
    this._obeliskFanHits=0;
    this._earthsplittersCast=0;
    this._earthsplitterHits=0;
    this._teleportsCast=0;
    this._teleportDistance=0;
    this._stealthCasts=0;
    this._stealthSeconds=0;
    this._rageCasts=0;
    this._rageSeconds=0;
    this._shieldAoeCasts=0;
    this._shieldAoeHits=0;
    this._fireballCasts=0;
    this._fireballHits=0;
    this._chainCasts=0;
    this._chainHits=0;
    this._beamCasts=0;
    this._voidstepCasts=0;
    this._voidstepExecutes=0;
    this._mirrorBladeProcs=0;
    this._mirrorBladeKills=0;
    this._mirrorBladeCooldown=0;
    this._mirrorVeilProcs=0;
    this._mirrorVeilKills=0;
    this._mirrorVeilCooldown=0;
    this._mirrorEchoProcs=0;
    this._mirrorEchoKills=0;
    this._mirrorEchoCooldown=0;
    this._mirrorPotionUses=0;
    this._mirrorPotionKills=0;
    this._mirrorPotionTimer=0;
    this._riftPulseProcs=0;
    this._riftPulseKills=0;
    this._riftPulseCooldown=0;
    this._riftAegisProcs=0;
    this._riftAegisKills=0;
    this._riftAegisCooldown=0;
    this._riftPotionUses=0;
    this._riftPotionKills=0;
    this._riftSlashProcs=0;
    this._riftSlashKills=0;
    this._riftSlashCooldown=0;
    this._obeliskEchoProcs=0;
    this._obeliskEchoKills=0;
    this._obeliskEchoCooldown=0;
    this._obeliskWardProcs=0;
    this._obeliskWardKills=0;
    this._obeliskWardCooldown=0;
    this._obeliskWardTimer=0;
    this._obeliskStrikeProcs=0;
    this._obeliskStrikeKills=0;
    this._obeliskStrikeCooldown=0;
    this._obeliskPotionUses=0;
    this._obeliskPotionKills=0;
    this._obeliskPotionTimer=0;
    this._mirrorDashSurvived=0;
    this._riftNovaSurvived=0;
    this._obeliskStormSurvived=0;
    this._shadowAwakenings=0;
    this._wellSustainBlessings=0;
    this._wellSustainVictories=0;
    this._beamImpacts=0;
    this._backstabCasts=0;
    this._backstabKills=0;
    this._shadowstepCasts=0;
    this._shadowstepFinishes=0;
    this._mirrorDashBossKills=0;
    this._riftNovaBossKills=0;
    this._obeliskStormBossKills=0;
    this._bossLegendaryDrops=0;
    this._potionsUsed=0;
    this._flawlessVictories=0;
    this._shopPurchases=0;
    this._shopSales=0;
    this._chestsOpened=0;
    this._shrineUses=0;
    this._stairsDescended=0;
    this._levelUpsGained=0;
    this._spellsCast=0;
    this._meleeHits=0;
    this._specialAttacksUsed=0;
    this._dodgesPerformed=0;
    this._meleeCrits=0;
    this._rangedHits=0;
    this._enemyProjectileHitsTaken=0;
    this._eliteKills=0;
    this._itemsPickedUp=0;
    this._goldPickups=0;
    this._hazardHitsTaken=0;
    this._hitsTaken=0;
    this._ringEquips=0;
    this._weaponEquips=0;
    this._armorEquips=0;
    this._itemsDropped=0;
    this._abyssRiftsUsed=0;
    this._riftEmpowerments=0;
    this._voidObelisksUsed=0;
    this._obeliskBoons=0;
    this._wellMercyCharges=0;
    this._wellSustainTimer=0;
    this._lastRelicFloor=0;
    this._lastWellFloor=0;
    this._lastRiftFloor=0;
    this._lastObeliskFloor=0;
    this._fpsSmoothed=60;
    this.initPlayer(playerClass);
    Achievements.reset();
    this.generateFloor();
    this.initInput();
    this.initSpellBar();
    this._ensureHudRefs();
    this._applyDebugOverlayVisibility();
    this._resetUICaches();
    this._applyDebugOverlayVisibility();
    
    this.running=true;
    this.lastTime=performance.now();
    requestAnimationFrame(t=>this.loop(t));
  },
  
});
