'use strict';
// =============================================
// ACHIEVEMENTS
// =============================================
const Achievements = {
  list:[
    {id:'first_blood',name:'Pierwsza Krew',desc:'Zabij pierwszego wroga',icon:'🗡️',check:g=>g.totalKills>=1,reward:'+5 Max HP',apply:p=>{p.maxHp+=5;p.hp+=5;},done:false},
    {id:'killer_10',name:'Łowca',desc:'Zabij 10 wrogów',icon:'💀',check:g=>g.totalKills>=10,reward:'+2 ATK',apply:p=>{p.atk+=2;},done:false},
    {id:'killer_50',name:'Rzeźnik',desc:'Zabij 50 wrogów',icon:'☠️',check:g=>g.totalKills>=50,reward:'+5 ATK',apply:p=>{p.atk+=5;},done:false},
    {id:'killer_100',name:'Pogromca',desc:'Zabij 100 wrogów',icon:'👹',check:g=>g.totalKills>=100,reward:'+10 ATK +20 HP',apply:p=>{p.atk+=10;p.maxHp+=20;p.hp+=20;},done:false},
    {id:'rich_100',name:'Zbieracz',desc:'Zbierz 100 złota łącznie',icon:'💰',check:g=>g.totalGold>=100,reward:'+10% Gold Find',apply:p=>{if(!p.talents)p.talents={};p.talents.goldFind=(p.talents.goldFind||0)+.1;},done:false},
    {id:'rich_500',name:'Bogacz',desc:'Zbierz 500 złota łącznie',icon:'👑',check:g=>g.totalGold>=500,reward:'+25% Gold Find',apply:p=>{if(!p.talents)p.talents={};p.talents.goldFind=(p.talents.goldFind||0)+.25;},done:false},
    {id:'floor_3',name:'Głęboko',desc:'Dotrzyj do 3. piętra',icon:'📍',check:g=>g.floor>=3,reward:'+10 Max HP +5 Max MP',apply:p=>{p.maxHp+=10;p.hp+=10;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'floor_5',name:'Wytrwały',desc:'Dotrzyj do 5. piętra',icon:'🏔️',check:g=>g.floor>=5,reward:'+3 DEF',apply:p=>{p.def+=3;},done:false},
    {id:'floor_10',name:'Legenda',desc:'Dotrzyj do ostatniego piętra',icon:'🌟',check:g=>g.floor>=10,reward:'+10 ATK +5 DEF',apply:p=>{p.atk+=10;p.def+=5;},done:false},
    {id:'boss_1',name:'Pogromca Bossów',desc:'Pokonaj pierwszego bossa',icon:'🏆',check:g=>g._bossKills>=1,reward:'+15 Max HP',apply:p=>{p.maxHp+=15;p.hp+=15;},done:false},
    {id:'level_5',name:'Weteran',desc:'Osiągnij poziom 5',icon:'⬆️',check:g=>g.player&&g.player.level>=5,reward:'+2 ATK +2 DEF',apply:p=>{p.atk+=2;p.def+=2;},done:false},
    {id:'combo_5',name:'Kombomaster',desc:'Osiągnij combo x5',icon:'🔥',check:g=>g._maxCombo>=5,reward:'+10% Krytyk',apply:p=>{p.critChance+=.1;},done:false},
    {id:'event_3',name:'Badacz Reliktów',desc:'Aktywuj 3 Tajemnicze Relikty',icon:'🜂',check:g=>(g._mysticEvents||0)>=3,reward:'+3 ATK +10 Max MP',apply:p=>{p.atk+=3;p.maxMp+=10;p.mp+=10;},done:false},
    {id:'echo_2',name:'Szept Pustki',desc:'Doświadcz 2 Echa Reliktu',icon:'🌌',check:g=>(g._echoVisions||0)>=2,reward:'+5% Krytyk +10 Max MP',apply:p=>{p.critChance+=.05;p.maxMp+=10;p.mp+=10;},done:false},
    {id:'shadowdance_3',name:'Wir Cieni',desc:'Wykonaj 3 Tańce Ostrzy',icon:'🩸',check:g=>(g._shadowDances||0)>=3,reward:'+2 ATK +5% Uniku',apply:p=>{p.atk+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.05;},done:false},
    {id:'well_echo_2',name:'Echo Studni',desc:'Przyjmij 2 Echa Studni Cieni',icon:'🕳️',check:g=>(g._wellEchoes||0)>=2,reward:'+3% Krytyk +5 Max HP',apply:p=>{p.critChance+=.03;p.maxHp+=5;p.hp+=5;},done:false},
    {id:'ring_legendary',name:'Korona Cienia',desc:'Załóż legendarny pierścień',icon:'💍',check:g=>!!(g.player&&g.player.equipment&&g.player.equipment.ring&&g.player.equipment.ring.rarity==='legendary'),reward:'+5 Max MP +2% Krytyk',apply:p=>{p.maxMp+=5;p.mp+=5;p.critChance+=.02;},done:false},
    {id:'mirage_3',name:'Łamacz Miraży',desc:'Pokonaj 3 elity Mirażowe',icon:'🌫️',check:g=>(g._mirageElitesSlain||0)>=3,reward:'+2 DEF +3% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.03;},done:false},
    {id:'mirror_executor_8',name:'Kat Zwierciadeł',desc:'Pokonaj 8 Egzekutorów Mirażu',icon:'🫥',check:g=>(g._mirrorExecutorsSlain||0)>=8,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_assassin_8',name:'Łowca Odbić',desc:'Pokonaj 8 Lustrzanych Skrytobójców',icon:'🪞',check:g=>(g._mirrorAssassinsSlain||0)>=8,reward:'+2 ATK +4% Uniku',apply:p=>{p.atk+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_priestess_8',name:'Prorok Odbić',desc:'Pokonaj 8 Kapłanek Zwierciadeł',icon:'🔹',check:g=>(g._mirrorPriestessesSlain||0)>=8,reward:'+2 DEF +5 Max MP',apply:p=>{p.def+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_herald_8',name:'Zwiastun Zwierciadeł',desc:'Pokonaj 8 Heroldów Mirażu',icon:'✨',check:g=>(g._mirrorHeraldsSlain||0)>=8,reward:'+2 ATK +1 DEF',apply:p=>{p.atk+=2;p.def+=1;},done:false},
    {id:'mirror_lancer_8',name:'Pęknięta Włócznia',desc:'Pokonaj 8 Włóczników Zwierciadła',icon:'🔱',check:g=>(g._mirrorLancersSlain||0)>=8,reward:'+2 ATK +4 Max HP',apply:p=>{p.atk+=2;p.maxHp+=4;p.hp+=4;},done:false},
    {id:'mirror_weaver_8',name:'Tkacz Pęknięć',desc:'Pokonaj 8 Tkaczy Mirażu',icon:'🪡',check:g=>(g._mirrorWeaversSlain||0)>=8,reward:'+2 DEF +5 Max MP',apply:p=>{p.def+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_dash_3',name:'Nietykalny Refleks',desc:'Przetrwaj 3 lustrzane doskoki bossa',icon:'🪞',check:g=>(g._mirrorDashSurvived||0)>=3,reward:'+8 Max HP +2 DEF',apply:p=>{p.maxHp+=8;p.hp+=8;p.def+=2;},done:false},
    {id:'rift_nova_3',name:'Rozrywacz Próżni',desc:'Przetrwaj 3 Szczelinowe Nove bossów',icon:'🌀',check:g=>(g._riftNovaSurvived||0)>=3,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'obelisk_storm_3',name:'Monolit Niezłomny',desc:'Przetrwaj 3 Burze Obelisku bossów',icon:'🗿',check:g=>(g._obeliskStormSurvived||0)>=3,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'rift_elite_6',name:'Łamacz Szczelin',desc:'Pokonaj 6 elit Szczelinowych',icon:'🜔',check:g=>(g._riftboundElitesSlain||0)>=6,reward:'+2 ATK +2 DEF',apply:p=>{p.atk+=2;p.def+=2;},done:false},
    {id:'rift_reaver_8',name:'Rzeźnik Szczeliny',desc:'Pokonaj 8 Rozpruwaczy Szczeliny',icon:'🜔',check:g=>(g._riftReaversSlain||0)>=8,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_sower_8',name:'Siewca Rozdarć',desc:'Pokonaj 8 Siewców Szczeliny',icon:'🌀',check:g=>(g._riftSowersSlain||0)>=8,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'obelisk_elite_6',name:'Kruszyciel Monolitów',desc:'Pokonaj 6 elit Obeliskowych',icon:'🗿',check:g=>(g._obeliskboundElitesSlain||0)>=6,reward:'+2 DEF +2 ATK',apply:p=>{p.def+=2;p.atk+=2;},done:false},
    {id:'obelisk_sentinel_8',name:'Burzyciel Bastionów',desc:'Pokonaj 8 Strażników Monolitu',icon:'🗿',check:g=>(g._obeliskSentinelsSlain||0)>=8,reward:'+2 DEF +10 Max HP',apply:p=>{p.def+=2;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'obelisk_augur_8',name:'Głos Monolitu',desc:'Pokonaj 8 Wieszczy Obelisku',icon:'🔷',check:g=>(g._obeliskAugursSlain||0)>=8,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_burst_12',name:'Arcykanał Szczeliny',desc:'Użyj 12 razy Szczelinowej Salwy',icon:'🜔',check:g=>(g._riftBurstsCast||0)>=12,reward:'+2 ATK +8 Max MP',apply:p=>{p.atk+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'rift_burst_hits_70',name:'Nadprzewodnik Próżni',desc:'Traf 70 razy Szczelinową Salwą',icon:'✨',check:g=>(g._riftBurstHits||0)>=70,reward:'+4% Krytyk +1 DEF',apply:p=>{p.critChance+=.04;p.def+=1;},done:false},
    {id:'rift_guard_10',name:'Bastion Rezonansu',desc:'Użyj 10 razy Bastionu Szczeliny',icon:'🛡️',check:g=>(g._riftGuardsCast||0)>=10,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'rift_guard_hits_55',name:'Opoka Próżni',desc:'Traf 55 razy Bastionem Szczeliny',icon:'🜔',check:g=>(g._riftGuardHits||0)>=55,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_blades_12',name:'Szermierz Szczeliny',desc:'Użyj 12 razy Ostrzy Szczeliny',icon:'🜔',check:g=>(g._riftBladesCast||0)>=12,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'rift_blades_hits_60',name:'Deszcz Próżni',desc:'Traf 60 razy Ostrzami Szczeliny',icon:'✨',check:g=>(g._riftBladeHits||0)>=60,reward:'+3% Krytyk +1 DEF',apply:p=>{p.critChance+=.03;p.def+=1;},done:false},
    {id:'obelisk_lance_12',name:'Sztych Monolitu',desc:'Użyj 12 razy Lancy Obelisku',icon:'🗿',check:g=>(g._obeliskLancesCast||0)>=12,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'obelisk_lance_hits_60',name:'Przebicie Monolitu',desc:'Traf 60 razy Lancą Obelisku',icon:'🔹',check:g=>(g._obeliskLanceHits||0)>=60,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'obelisk_crash_10',name:'Taran Monolitu',desc:'Użyj 10 razy Monolitowego Taranu',icon:'🗿',check:g=>(g._obeliskCrashesCast||0)>=10,reward:'+2 ATK +1 DEF',apply:p=>{p.atk+=2;p.def+=1;},done:false},
    {id:'obelisk_crash_hits_45',name:'Impakt Bastionu',desc:'Traf 45 razy Monolitowym Taranem',icon:'💥',check:g=>(g._obeliskCrashHits||0)>=45,reward:'+10 Max HP +1 DEF',apply:p=>{p.maxHp+=10;p.hp+=10;p.def+=1;},done:false},
    {id:'obelisk_fan_12',name:'Wachlarz Monolitu',desc:'Użyj 12 razy Odłamków Monolitu',icon:'🔷',check:g=>(g._obeliskFansCast||0)>=12,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'obelisk_fan_hits_70',name:'Szrapnel Pustki',desc:'Traf 70 razy Odłamkami Monolitu',icon:'✨',check:g=>(g._obeliskFanHits||0)>=70,reward:'+3% Krytyk +1 DEF',apply:p=>{p.critChance+=.03;p.def+=1;},done:false},
    {id:'earthsplitter_10',name:'Wstrząs Wojny',desc:'Użyj 10 razy Rozdarcia Ziemi',icon:'🪨',check:g=>(g._earthsplittersCast||0)>=10,reward:'+2 ATK +1 DEF',apply:p=>{p.atk+=2;p.def+=1;},done:false},
    {id:'earthsplitter_hits_50',name:'Pęknięty Front',desc:'Traf 50 razy Rozdarciem Ziemi',icon:'💥',check:g=>(g._earthsplitterHits||0)>=50,reward:'+12 Max HP +1 DEF',apply:p=>{p.maxHp+=12;p.hp+=12;p.def+=1;},done:false},
    {id:'teleport_18',name:'Migotanie Mirażu',desc:'Użyj 18 razy Teleportacji',icon:'🌀',check:g=>(g._teleportsCast||0)>=18,reward:'+6 Max MP +2% Krytyk',apply:p=>{p.maxMp+=6;p.mp+=6;p.critChance+=.02;},done:false},
    {id:'teleport_distance_120',name:'Tkanka Zwierciadeł',desc:'Pokonaj łącznie 120 pól Teleportacją',icon:'🪞',check:g=>(g._teleportDistance||0)>=120,reward:'+2 DEF +4% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'stealth_18',name:'Krok Mirażu',desc:'Użyj 18 razy Kroku Cienia',icon:'👤',check:g=>(g._stealthCasts||0)>=18,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'stealth_time_60',name:'Druga Skóra',desc:'Spędź łącznie 60s w ukryciu',icon:'🌫️',check:g=>(g._stealthSeconds||0)>=60,reward:'+2 DEF +4% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'rage_18',name:'Szczęk Bitewny',desc:'Użyj 18 razy Szału',icon:'😡',check:g=>(g._rageCasts||0)>=18,reward:'+3 ATK +6 Max HP',apply:p=>{p.atk+=3;p.maxHp+=6;p.hp+=6;},done:false},
    {id:'rage_time_75',name:'Wojna Bez Tchu',desc:'Spędź łącznie 75s w Szale',icon:'🔥',check:g=>(g._rageSeconds||0)>=75,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'shield_bash_18',name:'Żelazna Fala',desc:'Użyj 18 razy Uderzenia Tarczą',icon:'🛡️',check:g=>(g._shieldAoeCasts||0)>=18,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'shield_bash_hits_90',name:'Mur Uderzeniowy',desc:'Traf 90 razy Uderzeniem Tarczą',icon:'💥',check:g=>(g._shieldAoeHits||0)>=90,reward:'+2 ATK +1 DEF',apply:p=>{p.atk+=2;p.def+=1;},done:false},
    {id:'fireball_25',name:'Iskra Wojny',desc:'Użyj 25 razy Kuli Ognia',icon:'🔥',check:g=>(g._fireballCasts||0)>=25,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'fireball_hits_120',name:'Deszcz Płomieni',desc:'Traf 120 razy Kulą Ognia',icon:'💥',check:g=>(g._fireballHits||0)>=120,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'chain_20',name:'Burza Nad Otchłanią',desc:'Użyj 20 razy Burzy Otchłani',icon:'⚡',check:g=>(g._chainCasts||0)>=20,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'chain_hits_90',name:'Rozdział Błyskawic',desc:'Traf 90 razy Burzą Otchłani',icon:'🌩️',check:g=>(g._chainHits||0)>=90,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'beam_18',name:'Soczewka Pustki',desc:'Użyj 18 razy Promienia Pustki',icon:'🜄',check:g=>(g._beamCasts||0)>=18,reward:'+2 ATK +1 DEF',apply:p=>{p.atk+=2;p.def+=1;},done:false},
    {id:'voidstep_12',name:'Przeszycie Mroku',desc:'Użyj 12 razy Przebicia Pustki',icon:'🕳️',check:g=>(g._voidstepCasts||0)>=12,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'voidstep_exec_8',name:'Egzekutor Cieni',desc:'Wykonaj 8 egzekucji Przebiciem Pustki',icon:'☠️',check:g=>(g._voidstepExecutes||0)>=8,reward:'+3 ATK +2% Krytyk',apply:p=>{p.atk+=3;p.critChance+=.02;},done:false},
    {id:'rift_pulse_20',name:'Szczelinowy Rezonans',desc:'Aktywuj 20 razy puls pierścienia Szczeliny',icon:'💍',check:g=>(g._riftPulseProcs||0)>=20,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_pulse_kills_40',name:'Władca Rezonansu',desc:'Pokonaj 40 wrogów pulsem Szczeliny',icon:'🜔',check:g=>(g._riftPulseKills||0)>=40,reward:'+3 ATK +10 Max HP',apply:p=>{p.atk+=3;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'rift_slash_20',name:'Tasak Szczeliny',desc:'Aktywuj 20 razy rozcięcie broni Szczeliny',icon:'🪓',check:g=>(g._riftSlashProcs||0)>=20,reward:'+3 ATK +6 Max MP',apply:p=>{p.atk+=3;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_slash_kills_30',name:'Rozpad Krawędzi',desc:'Pokonaj 30 wrogów rozcięciem Szczeliny',icon:'🜔',check:g=>(g._riftSlashKills||0)>=30,reward:'+2 DEF +10 Max HP',apply:p=>{p.def+=2;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'rift_aegis_18',name:'Strażnik Szczeliny',desc:'Aktywuj 18 razy kirys Szczelinowej Straży',icon:'🛡️',check:g=>(g._riftAegisProcs||0)>=18,reward:'+3 DEF +6 Max MP',apply:p=>{p.def+=3;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_aegis_kills_25',name:'Pęknięta Reduta',desc:'Pokonaj 25 wrogów tarczą Szczeliny',icon:'🜔',check:g=>(g._riftAegisKills||0)>=25,reward:'+2 ATK +8 Max HP',apply:p=>{p.atk+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'rift_elixir_8',name:'Napór Szczeliny',desc:'Wypij 8 Eliksirów Szczeliny',icon:'🧪',check:g=>(g._riftPotionUses||0)>=8,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_elixir_kills_28',name:'Wir Rezonansu',desc:'Pokonaj 28 wrogów Eliksirem Szczeliny',icon:'🜔',check:g=>(g._riftPotionKills||0)>=28,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'obelisk_echo_20',name:'Echo Monolitu',desc:'Aktywuj 20 razy echo pierścienia Obelisku',icon:'💍',check:g=>(g._obeliskEchoProcs||0)>=20,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'obelisk_echo_kills_35',name:'Władca Monolitu',desc:'Pokonaj 35 wrogów echem Obelisku',icon:'🗿',check:g=>(g._obeliskEchoKills||0)>=35,reward:'+3 ATK +8 Max HP',apply:p=>{p.atk+=3;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'obelisk_ward_18',name:'Straż Monolitu',desc:'Aktywuj 18 razy wartę pancerza Obelisku',icon:'🛡️',check:g=>(g._obeliskWardProcs||0)>=18,reward:'+3 DEF +6 Max HP',apply:p=>{p.def+=3;p.maxHp+=6;p.hp+=6;},done:false},
    {id:'obelisk_ward_kills_25',name:'Bastion Egzekucji',desc:'Pokonaj 25 wrogów wartą Obelisku',icon:'🗿',check:g=>(g._obeliskWardKills||0)>=25,reward:'+2 ATK +2 DEF',apply:p=>{p.atk+=2;p.def+=2;},done:false},
    {id:'obelisk_strike_20',name:'Młot Monolitu',desc:'Aktywuj 20 razy uderzenie broni Obelisku',icon:'🔨',check:g=>(g._obeliskStrikeProcs||0)>=20,reward:'+3 ATK +1 DEF',apply:p=>{p.atk+=3;p.def+=1;},done:false},
    {id:'obelisk_strike_kills_30',name:'Rozbicie Monolitu',desc:'Pokonaj 30 wrogów uderzeniem Obelisku',icon:'💥',check:g=>(g._obeliskStrikeKills||0)>=30,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'obelisk_elixir_8',name:'Krew Monolitu',desc:'Wypij 8 Eliksirów Monolitu',icon:'🧪',check:g=>(g._obeliskPotionUses||0)>=8,reward:'+2 ATK +8 Max HP',apply:p=>{p.atk+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'obelisk_elixir_kills_25',name:'Natarcie Bastionu',desc:'Pokonaj 25 wrogów pod wpływem Eliksiru Monolitu',icon:'🗿',check:g=>(g._obeliskPotionKills||0)>=25,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'shadow_awake_2',name:'Przebudzenie Cienia',desc:'Aktywuj 2 Przebudzenia Cienia z Reliktu',icon:'🌑',check:g=>(g._shadowAwakenings||0)>=2,reward:'+5% Uniku +5 Max MP',apply:p=>{if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.05;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'well_sustain_2',name:'Łaska Studni',desc:'Zyskaj 2 błogosławieństwa sustain ze Studni Cieni',icon:'💜',check:g=>(g._wellSustainBlessings||0)>=2,reward:'+10 Max HP +5 Max MP',apply:p=>{p.maxHp+=10;p.hp+=10;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'well_victory_1',name:'Błogosławiony Finał',desc:'Ukończ run z aktywną Łaską Studni',icon:'🏁',check:g=>(g._wellSustainVictories||0)>=1,reward:'+3 DEF +5% Krytyk',apply:p=>{p.def+=3;p.critChance+=.05;},done:false},
    {id:'beam_hits_25',name:'Próżniowy Rezonans',desc:'Traf 25 razy Promieniem Pustki',icon:'🜄',check:g=>(g._beamImpacts||0)>=25,reward:'+4 ATK +5 Max MP',apply:p=>{p.atk+=4;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'backstab_18',name:'Sztych Mroku',desc:'Użyj 18 razy Ciosu w Plecy',icon:'💀',check:g=>(g._backstabCasts||0)>=18,reward:'+3 ATK +4 Max HP',apply:p=>{p.atk+=3;p.maxHp+=4;p.hp+=4;},done:false},
    {id:'backstab_kills_30',name:'Rzeźnik Zaułków',desc:'Pokonaj 30 wrogów Cięciem w Plecy',icon:'🩸',check:g=>(g._backstabKills||0)>=30,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'shadowstep_finish_10',name:'Krwawy Taniec',desc:'Dobij 10 wrogów Tańcem Ostrzy',icon:'🩸',check:g=>(g._shadowstepFinishes||0)>=10,reward:'+3 ATK +2 DEF',apply:p=>{p.atk+=3;p.def+=2;},done:false},
    {id:'shadowstep_18',name:'Tancerz Ostrzy',desc:'Użyj 18 razy Tańca Ostrzy',icon:'🗡️',check:g=>(g._shadowstepCasts||0)>=18,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_echo_20',name:'Puste Echo',desc:'Aktywuj 20 razy echo pierścienia Mirażu',icon:'💍',check:g=>(g._mirrorEchoProcs||0)>=20,reward:'+2 DEF +5 Max MP',apply:p=>{p.def+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_echo_kills_35',name:'Sala Luster',desc:'Pokonaj 35 wrogów echem Mirażu',icon:'🪞',check:g=>(g._mirrorEchoKills||0)>=35,reward:'+3% Krytyk +4% Uniku',apply:p=>{p.critChance+=.03;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_blade_20',name:'Szabla Zwierciadła',desc:'Aktywuj 20 razy lustrzane cięcie broni Mirażu',icon:'🗡️',check:g=>(g._mirrorBladeProcs||0)>=20,reward:'+3 ATK +5 Max MP',apply:p=>{p.atk+=3;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_blade_kills_30',name:'Krwawe Odbicie',desc:'Pokonaj 30 wrogów lustrzanym cięciem Mirażu',icon:'🪞',check:g=>(g._mirrorBladeKills||0)>=30,reward:'+2 DEF +4% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_veil_18',name:'Zwierciadlana Zasłona',desc:'Aktywuj 18 razy płaszcz Mirażu',icon:'🛡️',check:g=>(g._mirrorVeilProcs||0)>=18,reward:'+3 DEF +5 Max MP',apply:p=>{p.def+=3;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_veil_kills_25',name:'Rozprysk Luster',desc:'Pokonaj 25 wrogów zasłoną Mirażu',icon:'🪞',check:g=>(g._mirrorVeilKills||0)>=25,reward:'+2 ATK +4% Uniku',apply:p=>{p.atk+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_elixir_8',name:'Esencja Mirażu',desc:'Wypij 8 Eliksirów Mirażu',icon:'🧪',check:g=>(g._mirrorPotionUses||0)>=8,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'mirror_elixir_kills_25',name:'Lustrzana Rzeź',desc:'Pokonaj 25 wrogów pod wpływem Eliksiru Mirażu',icon:'🪞',check:g=>(g._mirrorPotionKills||0)>=25,reward:'+2 DEF +4% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_lord_2',name:'Pan Luster',desc:'Pokonaj 2 bossów posiadających Lustrzany Doskok',icon:'🪞',check:g=>(g._mirrorDashBossKills||0)>=2,reward:'+2 DEF +4% Uniku',apply:p=>{p.def+=2;if(!p.talents)p.talents={};p.talents.dodge=(p.talents.dodge||0)+.04;},done:false},
    {id:'mirror_lord_4',name:'Sala Tronowa Luster',desc:'Pokonaj 4 bossów posiadających Lustrzany Doskok',icon:'🪞',check:g=>(g._mirrorDashBossKills||0)>=4,reward:'+2 ATK +6 Max MP',apply:p=>{p.atk+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_lord_2',name:'Władca Rozdarcia',desc:'Pokonaj 2 bossów posiadających Szczelinową Novę',icon:'🌀',check:g=>(g._riftNovaBossKills||0)>=2,reward:'+2 DEF +6 Max MP',apply:p=>{p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'rift_lord_4',name:'Serce Rozdarcia',desc:'Pokonaj 4 bossów posiadających Szczelinową Novę',icon:'🌀',check:g=>(g._riftNovaBossKills||0)>=4,reward:'+3 ATK +1 DEF',apply:p=>{p.atk+=3;p.def+=1;},done:false},
    {id:'obelisk_lord_2',name:'Pan Monolitów',desc:'Pokonaj 2 bossów posiadających Burzę Obelisku',icon:'🗿',check:g=>(g._obeliskStormBossKills||0)>=2,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'obelisk_lord_4',name:'Wnętrze Monolitu',desc:'Pokonaj 4 bossów posiadających Burzę Obelisku',icon:'🗿',check:g=>(g._obeliskStormBossKills||0)>=4,reward:'+14 Max HP +1 DEF',apply:p=>{p.maxHp+=14;p.hp+=14;p.def+=1;},done:false},
    {id:'boss_legend_1',name:'Dziedzic Korony',desc:'Zdobądź 1 legendarny drop z bossa',icon:'👑',check:g=>(g._bossLegendaryDrops||0)>=1,reward:'+6 Max HP +3 Max MP',apply:p=>{p.maxHp+=6;p.hp+=6;p.maxMp+=3;p.mp+=3;},done:false},
    {id:'boss_legend_3',name:'Skarbiec Tronowy',desc:'Zdobądź 3 legendarne dropy z bossów',icon:'💎',check:g=>(g._bossLegendaryDrops||0)>=3,reward:'+3 ATK +2 DEF',apply:p=>{p.atk+=3;p.def+=2;},done:false},
    {id:'flawless_win_1',name:'Nieskazitelny Triumf',desc:'Wygraj run bez użycia mikstur',icon:'✨',check:g=>(g._flawlessVictories||0)>=1,reward:'+2 DEF +4% Krytyk',apply:p=>{p.def+=2;p.critChance+=.04;},done:false},
    {id:'flawless_win_2',name:'Korona Dyscypliny',desc:'Wygraj 2 runy bez użycia mikstur',icon:'👑',check:g=>(g._flawlessVictories||0)>=2,reward:'+12 Max HP +6 Max MP',apply:p=>{p.maxHp+=12;p.hp+=12;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'well_victory_2',name:'Pieczęć Studni',desc:'Ukończ 2 runy z aktywną Łaską Studni',icon:'🏁',check:g=>(g._wellSustainVictories||0)>=2,reward:'+2 DEF +8 Max MP',apply:p=>{p.def+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'shop_buy_10',name:'Klient Kupca',desc:'Kup 10 przedmiotów w sklepie',icon:'🛒',check:g=>(g._shopPurchases||0)>=10,reward:'+20 Max HP',apply:p=>{p.maxHp+=20;p.hp+=20;},done:false},
    {id:'shop_buy_25',name:'Magnat Karawan',desc:'Kup 25 przedmiotów w sklepie',icon:'🛍️',check:g=>(g._shopPurchases||0)>=25,reward:'+2 ATK +10 Max HP',apply:p=>{p.atk+=2;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'shop_sell_10',name:'Handlarz Cieni',desc:'Sprzedaj 10 przedmiotów w sklepie',icon:'💱',check:g=>(g._shopSales||0)>=10,reward:'+10 Max MP +2 DEF',apply:p=>{p.maxMp+=10;p.mp+=10;p.def+=2;},done:false},
    {id:'shop_sell_25',name:'Król Targu',desc:'Sprzedaj 25 przedmiotów w sklepie',icon:'💱',check:g=>(g._shopSales||0)>=25,reward:'+2 DEF +8 Max MP',apply:p=>{p.def+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'chest_15',name:'Łowca Skarbów',desc:'Otwórz 15 skrzyń',icon:'📦',check:g=>(g._chestsOpened||0)>=15,reward:'+1 ATK +1 DEF +5 Max HP',apply:p=>{p.atk+=1;p.def+=1;p.maxHp+=5;p.hp+=5;},done:false},
    {id:'chest_30',name:'Pan Kufrów',desc:'Otwórz 30 skrzyń',icon:'🗝️',check:g=>(g._chestsOpened||0)>=30,reward:'+2 ATK +2 DEF',apply:p=>{p.atk+=2;p.def+=2;},done:false},
    {id:'shrine_5',name:'Pielgrzym Mocy',desc:'Użyj kapliczki 5 razy',icon:'✨',check:g=>(g._shrineUses||0)>=5,reward:'+6 Max MP +3% Krytyk',apply:p=>{p.maxMp+=6;p.mp+=6;p.critChance+=.03;},done:false},
    {id:'shrine_10',name:'Wybraniec Ołtarzy',desc:'Użyj kapliczki 10 razy',icon:'✨',check:g=>(g._shrineUses||0)>=10,reward:'+2 ATK +8 Max MP',apply:p=>{p.atk+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'stairs_5',name:'W Głąb Otchłani',desc:'Zejdź 5 razy schodami w dół',icon:'🪜',check:g=>(g._stairsDescended||0)>=5,reward:'+2 DEF +8 Max HP',apply:p=>{p.def+=2;p.maxHp+=8;p.hp+=8;},done:false},
    {id:'stairs_12',name:'Rdzeń Labiryntu',desc:'Zejdź 12 razy schodami w dół',icon:'🪜',check:g=>(g._stairsDescended||0)>=12,reward:'+14 Max HP +6 Max MP',apply:p=>{p.maxHp+=14;p.hp+=14;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'levelups_8',name:'Weteran Rozwoju',desc:'Zdobądź 8 level-upów w runie',icon:'⬆️',check:g=>(g._levelUpsGained||0)>=8,reward:'+1 ATK +5 Max MP',apply:p=>{p.atk+=1;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'spells_50',name:'Arkanista',desc:'Rzuć 50 zaklęć',icon:'🔮',check:g=>(g._spellsCast||0)>=50,reward:'+2 ATK +5 Max MP',apply:p=>{p.atk+=2;p.maxMp+=5;p.mp+=5;},done:false},
    {id:'melee_40',name:'Mistrz Ostrza',desc:'Traf 40 razy atakiem wręcz',icon:'⚔️',check:g=>(g._meleeHits||0)>=40,reward:'+2 ATK +2 DEF',apply:p=>{p.atk+=2;p.def+=2;},done:false},
    {id:'special_20',name:'Mistrz Technik',desc:'Użyj 20 ataków specjalnych',icon:'💥',check:g=>(g._specialAttacksUsed||0)>=20,reward:'+2 ATK +5 Max HP',apply:p=>{p.atk+=2;p.maxHp+=5;p.hp+=5;},done:false},
    {id:'dodge_20',name:'Nietykalny Cień',desc:'Wykonaj 20 uników',icon:'💨',check:g=>(g._dodgesPerformed||0)>=20,reward:'+2 DEF +3% Krytyk',apply:p=>{p.def+=2;p.critChance+=.03;},done:false},
    {id:'crit_melee_20',name:'Precyzyjne Ostrze',desc:'Zadaj 20 trafień krytycznych wręcz',icon:'🎯',check:g=>(g._meleeCrits||0)>=20,reward:'+3 ATK +5% Krytyk',apply:p=>{p.atk+=3;p.critChance+=.05;},done:false},
    {id:'ranged_40',name:'Strzelec Otchłani',desc:'Traf 40 razy pociskami dystansowymi',icon:'🏹',check:g=>(g._rangedHits||0)>=40,reward:'+2 ATK +8 Max MP',apply:p=>{p.atk+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'enemy_proj_hit_30',name:'Skóra ze Stali',desc:'Przyjmij 30 trafień pociskami wroga',icon:'🛡️',check:g=>(g._enemyProjectileHitsTaken||0)>=30,reward:'+3 DEF +12 Max HP',apply:p=>{p.def+=3;p.maxHp+=12;p.hp+=12;},done:false},
    {id:'elite_kills_20',name:'Pogromca Elit',desc:'Pokonaj 20 elitarnych wrogów',icon:'⚜️',check:g=>(g._eliteKills||0)>=20,reward:'+2 ATK +2 DEF +10 Max HP',apply:p=>{p.atk+=2;p.def+=2;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'loot_pickups_30',name:'Zbieracz Łupów',desc:'Podnieś 30 przedmiotów z podłogi',icon:'🎒',check:g=>(g._itemsPickedUp||0)>=30,reward:'+1 ATK +1 DEF +6 Max MP',apply:p=>{p.atk+=1;p.def+=1;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'gold_pickups_80',name:'Chciwy Kolekcjoner',desc:'Podnieś 80 stosów złota z podłogi',icon:'💰',check:g=>(g._goldPickups||0)>=80,reward:'+20 Max HP +10% Gold Find',apply:p=>{p.maxHp+=20;p.hp+=20;if(!p.talents)p.talents={};p.talents.goldFind=(p.talents.goldFind||0)+.1;},done:false},
    {id:'hazard_hits_25',name:'Hartowany w Ogniu',desc:'Przyjmij 25 trafień od zagrożeń środowiskowych',icon:'🔥',check:g=>(g._hazardHitsTaken||0)>=25,reward:'+3 DEF +12 Max HP',apply:p=>{p.def+=3;p.maxHp+=12;p.hp+=12;},done:false},
    {id:'hits_taken_120',name:'Niezłomny',desc:'Przyjmij 120 trafień',icon:'🗿',check:g=>(g._hitsTaken||0)>=120,reward:'+4 DEF +20 Max HP',apply:p=>{p.def+=4;p.maxHp+=20;p.hp+=20;},done:false},
    {id:'ring_equips_10',name:'Mistrz Pierścieni',desc:'Załóż 10 pierścieni',icon:'💍',check:g=>(g._ringEquips||0)>=10,reward:'+2 DEF +8 Max MP',apply:p=>{p.def+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'weapon_equips_12',name:'Zbrojmistrz Ostrza',desc:'Załóż 12 broni',icon:'⚔️',check:g=>(g._weaponEquips||0)>=12,reward:'+3 ATK +5% Krytyk',apply:p=>{p.atk+=3;p.critChance+=.05;},done:false},
    {id:'armor_equips_10',name:'Żelazna Garda',desc:'Załóż 10 pancerzy',icon:'🛡️',check:g=>(g._armorEquips||0)>=10,reward:'+4 DEF +12 Max HP',apply:p=>{p.def+=4;p.maxHp+=12;p.hp+=12;},done:false},
    {id:'items_dropped_20',name:'Czyściciel Plecaka',desc:'Wyrzuć 20 przedmiotów z ekwipunku',icon:'🧹',check:g=>(g._itemsDropped||0)>=20,reward:'+1 ATK +2 DEF',apply:p=>{p.atk+=1;p.def+=2;},done:false},
    {id:'rift_3',name:'Pęknięta Granica',desc:'Zamknij 3 Szczeliny Otchłani',icon:'🌀',check:g=>(g._abyssRiftsUsed||0)>=3,reward:'+2 ATK +10 Max HP',apply:p=>{p.atk+=2;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'rift_emp_2',name:'Znak Otchłani',desc:'Zyskaj 2 wzmocnienia ze Szczeliny',icon:'🜁',check:g=>(g._riftEmpowerments||0)>=2,reward:'+3% Krytyk +6 Max MP',apply:p=>{p.critChance+=.03;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'obelisk_3',name:'Szept Monolitu',desc:'Aktywuj 3 Obeliski Pustki',icon:'🗿',check:g=>(g._voidObelisksUsed||0)>=3,reward:'+2 DEF +8 Max MP',apply:p=>{p.def+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'obelisk_boon_2',name:'Pieczęć Pustki',desc:'Zyskaj 2 błogosławieństwa Obelisku',icon:'🔮',check:g=>(g._obeliskBoons||0)>=2,reward:'+2 ATK +3% Krytyk',apply:p=>{p.atk+=2;p.critChance+=.03;},done:false},
    {id:'abyss_enter',name:'Za Krawędzią',desc:'Zejdź do Otchłani po zwycięstwie',icon:'🕳️',check:g=>!!g.endlessMode,reward:'+10 Max HP +3 ATK',apply:p=>{p.maxHp+=10;p.hp+=10;p.atk+=3;},done:false},
    {id:'abyss_3',name:'Echo Głębin',desc:'Dotrzyj na 3. piętro Otchłani',icon:'🌑',check:g=>g.endlessMode&&g.floor>=13,reward:'+3 DEF +10 Max MP',apply:p=>{p.def+=3;p.maxMp+=10;p.mp+=10;},done:false},
    {id:'abyss_5',name:'Głębia Szaleństwa',desc:'Dotrzyj na 5. piętro Otchłani',icon:'🕳️',check:g=>g.endlessMode&&g.floor>=15,reward:'+4 ATK +4 DEF',apply:p=>{p.atk+=4;p.def+=4;},done:false},
    {id:'abyss_10',name:'Dno, Którego Nie Ma',desc:'Dotrzyj na 10. piętro Otchłani',icon:'🌌',check:g=>g.endlessMode&&g.floor>=20,reward:'+25 Max HP +5 ATK +5 DEF',apply:p=>{p.maxHp+=25;p.hp+=25;p.atk+=5;p.def+=5;},done:false},
    {id:'minions_10',name:'Władca Marionetek',desc:'Wskrześ 10 sług',icon:'💀',check:g=>(g._minionsRaised||0)>=10,reward:'+10 Max MP +2 ATK',apply:p=>{p.maxMp+=10;p.mp+=10;p.atk+=2;},done:false},
    {id:'minion_kills_30',name:'Armia Umarłych',desc:'Twoje sługi pokonają 30 wrogów',icon:'⚰️',check:g=>(g._minionKills||0)>=30,reward:'+3 ATK +10 Max HP',apply:p=>{p.atk+=3;p.maxHp+=10;p.hp+=10;},done:false},
    {id:'corpse_burst_10',name:'Profanator',desc:'Użyj 10 razy Eksplozji Zwłok',icon:'🩸',check:g=>(g._corpseBurstsCast||0)>=10,reward:'+2 ATK +8 Max MP',apply:p=>{p.atk+=2;p.maxMp+=8;p.mp+=8;},done:false},
    {id:'dark_pact_8',name:'Cena Mocy',desc:'Zawrzyj 8 Mrocznych Paktów',icon:'🕯️',check:g=>(g._darkPactsCast||0)>=8,reward:'+12 Max HP +6 Max MP',apply:p=>{p.maxHp+=12;p.hp+=12;p.maxMp+=6;p.mp+=6;},done:false},
    {id:'scrolls_5',name:'Uczony Lochu',desc:'Odczytaj 5 zwojów',icon:'📜',check:g=>(g._scrollsUsed||0)>=5,reward:'+6 Max MP +1 DEF',apply:p=>{p.maxMp+=6;p.mp+=6;p.def+=1;},done:false},
    {id:'scrolls_15',name:'Archiwista Pustki',desc:'Odczytaj 15 zwojów',icon:'📚',check:g=>(g._scrollsUsed||0)>=15,reward:'+2 ATK +2 DEF +6 Max MP',apply:p=>{p.atk+=2;p.def+=2;p.maxMp+=6;p.mp+=6;},done:false},
  ],
  
  checkAll(game){
    for(const ach of this.list){
      if(ach.done)continue;
      if(ach.check(game)){
        ach.done=true;
        ach.apply(game.player);
        game._showAchievement(ach);
        game.log(`🏆 Osiągnięcie: ${ach.name}! ${ach.reward}`,'boss');
      }
    }
  },
  
  getCompleted(){return this.list.filter(a=>a.done).length;},
  getTotal(){return this.list.length;},
  
  reset(){for(const a of this.list)a.done=false;}
};

// SpellDB moved to content/spells.js

